_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 20
k_folds:
    value: 5
learning_rate:
    value: 0.001
